backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: static/img
i18n:
  structure: single_file
  locales: [en, de]
  default_locale: en

collections:
  - name: 'seo'
    i18n: true
    label: 'SEO'
    files:
      - name: homepage
        label: Homepage
        i18n: true
        file: content/seo/homepage.yml
        fields:
          - { label: Title, name: title, i18n: true }
          - {
              label: Description,
              name: description,
              required: false,
              i18n: true,
            }
